sudo: required

language: c

before_install:
  ## r-travis by Craig Citro et al
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget r-cran-dplyr r-cran-ggplot2 r-cran-googlesheets r-cran-Hmisc r-cran-lubridate
  - ./travis-tool.sh install_aptget r-cran-knitr r-cran-magrittr r-cran-readr r-cran-rdrop2 r-cran-rvest
  - ./travis-tool.sh install_aptget r-cran-slackr r-cran-xml2
  - ./travis-tool.sh install_github artemklevtsov/RGA jimhester/gmailr

script:
  - ./travis-tool.sh run_tests
  
after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  slack: us-lab:xTJ3Yh37JO4luAh9Yx6gXTck
  email: false
